[tools]
go = "1.26"

[tasks.refresh]
run = "go run . create-secret"
description = "Generate refresh token"

[tasks.server]
run = "go run . server"
description = "Run server"

[tasks.feed]
run = "go run . generate-feed"
description = "One time generation of feed"
